import { RegionConfig, RegionId, PhenologyStage } from '../types';

export const REGION_CONFIGS: Record<RegionId, RegionConfig> = {
  xishuangbanna: {
    id: 'xishuangbanna',
    name: '云南西双版纳',
    subName: '景洪 · 勐腊核心产区',
    country: '中国',
    flag: '🇨🇳',
    globalShare: 4.2,
    lat: 21.48,
    lon: 101.56,
    annualTappingDays: 195,
    description: '国内最主要天胶产区之一。受季风气候影响明显，冬春低温干旱落叶休割，7-10月雨水充沛进入全年旺产高峰。',
    monthlyPhenology: {
      1: 'OFF',
      2: 'OFF',
      3: 'START',
      4: 'RISING',
      5: 'RISING',
      6: 'RISING',
      7: 'PEAK',
      8: 'PEAK',
      9: 'PEAK',
      10: 'PEAK',
      11: 'FALLING',
      12: 'OFF',
    },
  },
  hainan: {
    id: 'hainan',
    name: '海南岛主产区',
    subName: '白沙 · 儋州中西部林区',
    country: '中国',
    flag: '🇨🇳',
    globalShare: 2.1,
    lat: 19.52,
    lon: 109.58,
    annualTappingDays: 210,
    description: '国内另一大核心胶园集群。夏秋两季易受南海热带风暴及台风暴雨侵袭，年停割期一般在 12 月下旬至次年 3 月中旬。',
    monthlyPhenology: {
      1: 'OFF',
      2: 'OFF',
      3: 'START',
      4: 'RISING',
      5: 'RISING',
      6: 'RISING',
      7: 'RISING',
      8: 'PEAK',
      9: 'PEAK',
      10: 'PEAK',
      11: 'FALLING',
      12: 'OFF',
    },
  },
  thailand_south: {
    id: 'thailand_south',
    name: '泰国南部核心产区',
    subName: '素叻他尼 · 宋卡/合艾',
    country: '泰国',
    flag: '🇹🇭',
    globalShare: 24.5,
    lat: 7.18,
    lon: 100.59,
    annualTappingDays: 230,
    description: '全球天然橡胶绝对心脏地带！占全泰橡胶产量超 65%。每年 2-4 月落叶停割，10 月至次年 1 月为全球最大规模的高产旺产季。',
    monthlyPhenology: {
      1: 'PEAK',
      2: 'FALLING',
      3: 'OFF',
      4: 'OFF',
      5: 'START',
      6: 'RISING',
      7: 'RISING',
      8: 'RISING',
      9: 'PEAK',
      10: 'PEAK',
      11: 'PEAK',
      12: 'PEAK',
    },
  },
  vietnam: {
    id: 'vietnam',
    name: '越南东南部产区',
    subName: '平福 · 同奈胶园带',
    country: '越南',
    flag: '🇻🇳',
    globalShare: 8.8,
    lat: 11.53,
    lon: 106.88,
    annualTappingDays: 225,
    description: '全球第三大天然橡胶出口国。胶园树龄轻、单产水平高，通常 3 月低产停割，5 月开割，9-12 月为高产旺季。',
    monthlyPhenology: {
      1: 'FALLING',
      2: 'OFF',
      3: 'OFF',
      4: 'START',
      5: 'RISING',
      6: 'RISING',
      7: 'RISING',
      8: 'RISING',
      9: 'PEAK',
      10: 'PEAK',
      11: 'PEAK',
      12: 'FALLING',
    },
  },
  indonesia: {
    id: 'indonesia',
    name: '印尼苏门答腊产区',
    subName: '棉兰 · 巨港主产林带',
    country: '印尼',
    flag: '🇮🇩',
    globalShare: 22.0,
    lat: 3.59,
    lon: 98.67,
    annualTappingDays: 250,
    description: '全球第二大产胶国。处于赤道热带雨林带，全年均有割胶作业，无严格集中休割期，受偶发极端强降雨和胶工短缺影响较大。',
    monthlyPhenology: {
      1: 'RISING',
      2: 'FALLING',
      3: 'RISING',
      4: 'RISING',
      5: 'RISING',
      6: 'RISING',
      7: 'PEAK',
      8: 'PEAK',
      9: 'PEAK',
      10: 'PEAK',
      11: 'PEAK',
      12: 'RISING',
    },
  },
};

export const PHENOLOGY_INFO: Record<PhenologyStage, { label: string; color: string; bg: string; desc: string }> = {
  OFF: {
    label: '休割停割',
    color: 'text-slate-400',
    bg: 'bg-slate-800 border-slate-700',
    desc: '橡胶树落叶与抽叶恢复期，全林停止割胶，无新增乳胶产出。',
  },
  START: {
    label: '试割开割',
    color: 'text-emerald-400',
    bg: 'bg-emerald-950/60 border-emerald-800/80',
    desc: '新叶完全老化变绿，林区陆续开割试刀，胶水干含较低，产出温和启动。',
  },
  RISING: {
    label: '增产爬坡',
    color: 'text-teal-300',
    bg: 'bg-teal-950/70 border-teal-700/80',
    desc: '胶水产量与干含双双稳步攀升，加工厂开工负荷逐渐加码。',
  },
  PEAK: {
    label: '高产旺季',
    color: 'text-amber-300',
    bg: 'bg-amber-950/80 border-amber-500/80 ring-1 ring-amber-400/40',
    desc: '全年最高产阶段，单树出胶量达到峰值，原料释放决定全年供需胜负手。',
  },
  FALLING: {
    label: '减产收尾',
    color: 'text-orange-400',
    bg: 'bg-orange-950/70 border-orange-700/80',
    desc: '气温骤降或干旱诱发落叶，出胶量显著回落，逐步进入停割准备阶段。',
  },
};
